### ISSUE TITLE
Error when following getting started guide

### ISSUE THREAD

**Issue by vpavlin** [temporalio/temporalite#122]
Hi, I am starting my experiments with Temporal and the getting started docs resulted in an error for me.

Temporal started normally when I pre-created the missing directory, but Temporal should probably either create it, or the docs should mention it is needed

```
mkdir -p /home/vpavlin/.config/temporalite/db
```

## Expected Behavior

```
$ /home/vpavlin/devel/bin/temporalite start --namespace default
{"level":"info","ts":"2022-09-05T08:29:27.156+0200","msg":"Successfully saved cluster metadata.","component":"metadata-initializer","cluster-name":"active","logging-call-at":"fx.go:631"}
```

## Actual Behavior

```
$ /home/vpavlin/devel/bin/temporalite start --namespace default
2022/09/05 08:27:57 error setting up schema: stat /home/vpavlin/.config/temporalite/db: no such file or directory
```

## Steps to Reproduce the Problem

1. `go install github.com/temporalio/temporalite/cmd/temporalite@latest`
1. ` temporalite start --namespace default`

## Specifications

- Version:
- Platform:

**Comment by jlegrone** [comment]
This seems related to #99 which improved on the error message. I think we should also add a special case to create the directory if not exists when the db file path is [set to the default](https://github.com/temporalio/temporalite/blob/fbe98746a007a342bcd267626f990f9bf896a59c/internal/liteconfig/config.go#L86), since `$XDG_CONFIG_HOME/temporalite/db` is not going to exist with a fresh installation.

**Comment by lorensr** [comment]
Similar error on Mac:

```
temporalite start --namespace default
2022/09/22 15:20:07 error setting up schema: stat /Users/me/Library/Application Support/temporalite/db: no such file or directory
```

**Comment by hferentschik** [comment]
@vpavlin, @lorensr  - this should fix the issue https://github.com/temporalio/temporalite/pull/140 ;-)
